### PR TITLE
Ignore Puppet's `strict` setting when calling function without namespace

### LINKED ISSUE #1373: Calls to `Deprecation` function cause catalog compilation to fail if `strict` setting is set to `error`
In stdlib 9.0 many functions were namespaced and non-namespaced deprecated shims were introduced to maintain compatibility with modules that haven't yet switched over to using the namespaced versions.

This largely works as intended, but (originally in #1365) it's been noted that the `deprecation` function will actually fail a catalog compile when [`strict` is set to `error`](https://github.com/puppetlabs/puppetlabs-stdlib/blob/44b6065d9e43e7b5d2983c91f6753627ceed550b/lib/puppet/functions/deprecation.rb#L32-L33), and that this is also the default in the upcoming Puppet 8.

This makes it very difficult for users to upgrade to stdlib 9 unless they're prepared to turn the `strict` setting back to `off` or `warning` (and there are many other good reasons for setting `strict` to `error`).  Since lots of modules are now also being updated to use the namespaced versions (requiring stdlib 9.0), upgrading a single affected component module now means having to upgrade _all_ modules that use stdlib functions.

Possible solutions include:
* Still leaving the shims documented as deprecated, but removing the calls to the `deprecation` function
* Adjusting deprecation so that it never raises an error

(This issue replaces #1365 where 2 separate issues were being discussed)

### PR DESCRIPTION
**Pull request by alexjfisher**
Previously, when a user had the Puppet setting `strict` set to `error` (which is the default in Puppet 8), a call to one of stdlib's functions via the deprecated non-namespaced function would cause a hard failure instead of just logging a warning and calling the real namespaced function.

In this change, all of our shims have been updated to call `deprecation` with its new third parameter, (`use_strict_setting`), set to `false`. The non-namespaced versions will now only ever log warnings informing users to moved to the namespaced versions. It will not raise exceptions even if `strict` is set to `error`.

This change will make it much easier for users to migrate to stdlib 9 (and to upgrade modules that now depend on stdlib 9)

Fixes #1373

(Note, this PR description was updated after the `deprecation` function update was extracted into its own PR https://github.com/puppetlabs/puppetlabs-stdlib/pull/1378)

### CODE REVIEW

File: lib/puppet/functions/deprecation.rb [hunk 1]
```diff
@@ -1,38 +1,38 @@
...
+  #   (outputs as an error message), :off (no message / error is displayed) and :warning
+  #   (default, outputs a warning).
   dispatch :deprecation do
     param 'String', :key
     param 'String', :message
+    optional_param 'Boolean', :use_strict_setting
   end
 
-  def deprecation(key, message)
+  def deprecation(key, message, use_strict_setting = true) # rubocop:disable Style/OptionalBooleanParameter
```
Comment (bastelfreak) [inline lib/puppet/functions/deprecation.rb:19]: can the default for `use_strict_setting` maybe come from an environment variable? At the moment CI jobs on Puppet 8 fail if they use the legacy functions and that's a nice way to identify them. It would be helpful to have an easy way to identify them in the future.

Comment (chelnak) [reply lib/puppet/functions/deprecation.rb:19]: Can we have both?

**Comment by chelnak** [comment]
I don't feel strongly either way but I wonder if it would be cleaner to have the implementation and updates should be in separate PRs?

File: lib/puppet/functions/deprecation.rb (hunk 1 above)
Comment (alexjfisher) [reply lib/puppet/functions/deprecation.rb:19]: Not sure.  We _could_ but I think I'd lean towards keeping it simple.  The existing environment variable code already looked hacky without adding yet more.  Functions whose behaviour changes based on something other than the function inputs seem like an antipattern to me.  Let's not make it worse?

> that's a nice way to identify them
But was it 'nice'?  The current behaviour has actually forced us to make all modules _depend_ on stdlib 9 in a very short space of time. That may have caused more harm than good.

Maybe a new puppet-lint plugin would be a better way to identify calls to non-namespaced functions?

Comment (jhoblitt) [reply lib/puppet/functions/deprecation.rb:19]: I'm pretty sure that the road to hell is paved with env vars...

Comment (chelnak) [reply lib/puppet/functions/deprecation.rb:19]: A new linter would certainly do the job.

Comment (alexjfisher) [reply lib/puppet/functions/deprecation.rb:19]: Not a blocker though, so maybe let this stew over the weekend and if there aren't any objections get it merged and a release out Monday??

Comment (chelnak) [reply lib/puppet/functions/deprecation.rb:19]: Sounds good to me.

Thanks for jumping on this!

**Review by jhoblitt — APPROVED** [review]
I think this is probably the least painful path forward from the current situation. I hope that in the future we will do a better job of **not** introducing a deprecation and the replacement facility in the same release. Otherwise, `strict = error` will quickly become meaningless and/or users will change to `string = warn`.

File: lib/puppet/functions/deprecation.rb [hunk 2]
```diff
@@ -1,38 +1,38 @@
...
-    end
+
+    # Do nothing if using strict setting and strict is set to `off`
+    return if use_strict_setting && Puppet.settings[:strict] == :off
+
+    # Fail hard if using strict setting and strict is set to `error`
+    raise("deprecation. #{key}. #{message}") if use_strict_setting && Puppet.settings[:strict] == :error
+
+    # Otherwise raise a soft warning
+    # (unless the STDLIB_LOG_DEPRECATIONS has been set to `false`.  This is mainly for use in rspec-puppet testing to supress noise in logs)
```
Comment (ekohl) [inline lib/puppet/functions/deprecation.rb:34]:
```suggestion
    # (unless the STDLIB_LOG_DEPRECATIONS has been set to `false`.  This is mainly for use in rspec-puppet testing to suppress noise in logs)
```

**Review by ekohl — APPROVED** [review]
Makes sense to me.

File: lib/puppet/functions/deprecation.rb (hunk 2 above)
Comment (alexjfisher) [reply lib/puppet/functions/deprecation.rb]: Fixed

**Comment by chelnak** [comment]
How's everyone feeling about this today?

**Comment by bastelfreak** [comment]
> I don't feel strongly either way but I wonder if it would be cleaner to have the implementation and updates should be in separate PRs?

 I agree with @chelnak . @alexjfisher what do you think?

**Comment by alexjfisher** [comment]
@chelnak @bastelfreak I've split this into 2 commits and opened https://github.com/puppetlabs/puppetlabs-stdlib/pull/1378 with just the updates to the `deprecation` function.  If you approve and merge that one first, this one can go in second, and I'll update the description to match the single commit.

**Comment by chelnak** [comment]
Thank you!

**Comment by chelnak** [comment]
This PR should be ready for a rebase now!

**Review by chelnak — APPROVED** [review]

**Review by chelnak — APPROVED** [review]

**Review by chelnak — APPROVED** [review]

**Review by chelnak — APPROVED** [review]
